name: Azure Static Web Apps CI/CD

on:
#   Maual Test용
#   repository_dispatch:

  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
    paths:
      - 'board-app/**'
      - '!board-app/**.md'
    branches: [ main ]

jobs:
  static-analyze:
    name: Analyze unsing CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://git.io/codeql-language-support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: 'dev'

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main

    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    # ℹ️ Command-line programs to run using the OS shell.
    # 📚 https://git.io/JvXDl

    # ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
    #    and modify them (or add more) to build your code if your project
    #    uses a compiled language

    #- run: |
    #   make bootstrap
    #   make release

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      
  unit-test:
    runs-on: ubuntu-latest
    name: Unit Test using jest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action' 
        uses: actions/checkout@main
        with:
          ref: 'dev'        

      # 지정한 버전 node.js 설치
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: |
          echo 'Start Unit Test'

          cd board-app
          npm install
          npm run test

          echo 'Complete Unit Test'

  vuecli-build:
    needs: [ static-analyze, unit-test ]
    runs-on: ubuntu-latest
    name: vue-cli-service build
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action' 
        uses: actions/checkout@main
        with:
          ref: 'dev'

      # 지정한 버전 node.js 설치
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: |
          echo 'Start build Test'

          cd board-app
          npm install
          npm run build

          echo 'Complete build Test'
    
  build_and_deploy_job:
    needs: vuecli-build
    environment:
      name: staging
      url: 'https://lemon-pebble-0bb22af00.1.azurestaticapps.net'
      
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          ref: 'dev'
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_PEBBLE_0BB22AF00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/board-app" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          skip_app_build: 'false'
          app_build_command: 'npm run build'
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_PEBBLE_0BB22AF00 }}
          action: "close"
